language: node_js
node_js:
  - "4.1"
 # - 0.10.36


addons:
    apt:
        sources:
        - ubuntu-toolchain-r-test
        packages:
        - g++-4.8
env:
  global:
    - region="us-east-1"
    - CXX=g++-4.8
    - secure: "Rvx0CB2/YXQJ79DgcBY7CPtHd0fwa9lZXj2WHnfyPfbupnBdqS2MLih2RjrqR9Ca9alidiMTFUAmjTuIirXqjYtpYO5H/Fm/0Avukts82yhLZZ0kzBFKldwpQTjB21dSi6E6x/uM7bwRQ+WtlKc8LTCj+uzBmb2C5O4vO9VyTxSqrc4sYKhbW752ViunoWpNkVlSXaau5AF4/f/GnXbTnjppHHjRDfYkbuAoAoGYknoJbkkPstK2J2rVGXcYkTIgbF8lP3SfUjkz4v5nh3iRkWIGLrHzX2EhyAnW/+Q4cBngavKDtVpNtqDZEzVZdjOp3+K7Z5a+PEVQsUo0pm3GdmrgBOAapY2vVp041gGEWIvaDVFapzqEC8VFtm5nJfvA0jfI9p10aSe2AXrdDOAwTC80wTdpLPNrMDa/ay8cBLeIlQexaEmkkax2uo79wegQfDYEaz89zu8ftAdGlIO8rVoyYrRKFJvpwneuFnLw9difAMkF+LSCrA+atovEj95RM3/h/60jIwXxJ7EQo4Xclf659euAm/VNk+tXnEkTbY5IUKywqo2uT9WYiuTOZ5jbDdN3PBKZEGczOsFhFaChOZnx3amsNvLRgZoe9OM/2VMYZY/m2IQyQgD9YCp+dh0yF06PHP6lXBAECg21qZGiocfTP/d9sjqe6+PriVJ3Ce4="
    - secure: "osVaedMpR96FXOML+rb/6ZA43u5Kmc+5b+boivlKrSZ0G4CUiB8aNXVcsm9OrggAE3S+aBjN3GOkul/UmQpZL6Uv1mtDpp2/kVRs8dAlWKFC39KALX1e4YMYQRN5Xj+4y/dKW+xmxIuXLLnpWi+iQJvkD55U1AuY5N7zmvkogaTBs4X5Fj800WG1RirT7oprA4UMaBsqFctOcnZn09pb7cgYHAndgmBPprPzONckekMgG9gCRDvVE3ACi4f5QdZpf1u3gMh3O9N0lbfkiFiAR87vkbHHcPUd5rem1fJJG+M5GQCK651pGTd4JVmGwkee/FIVi5EQa3Ttx6JRVPVWIFAzhKv1tYgqYrvBBSNQriJrxvJ7nZpPpZGFlEd0jltF9IDwT8YGXrKsVOZX3GdyDu2e1WQKq9R+aaz/Q77pCGsQMIRngpBMF68rj4zhx/7uINk4Fb7LSb0eJer5hQP/86ZMuixZlw1zQFdxlM4gHzyBmwm6GdqaY5IbbSypqUkH5dsE7EGUK8UaV5cT443B1s/tzvIqEkqEXlYZLTPFaaVK6KCw0XZJxR8joDwJxvAOKlCBrYABbCvA7TGZ9GMwXm8F6d+cHnORffr1BEBFWr9tY4xpFQtYMhR2FkaFt60EirUM6B02C11p3DuHbCcFj7+7o5yjlc4LVvqu/j5tx3c="


install:
  - if [[ $TRAVIS_OS_NAME == "linux" ]]; then export CXX=g++-4.8; fi
  - $CXX --version
  - npm install -g gulp casperjs
  - npm install
  - gulp deploy_stage

after_success:
  - if [[ "$TRAVIS_BRANCH" != "master" ]]; then echo "Deployments are only done for the master branch. Current branch is $TRAVIS_BRANCH"; exit 0; fi
  - gulp --buildId=$TRAVIS_BUILD_ID --buildNumber=$TRAVIS_BUILD_NUMBER
  - gulp deploy_prod
  - node invalidate.js
